# Generated by Django 5.1.15 on 2026-06-10 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_conversionjob_project_conversionjob_uploaded_by'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(help_text="Ex: 'use_case_status', 'defect_created', 'sprint_created', 'weekly_report_submitted'", max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='teams.project')),
                ('target_users', models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='teams.team')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('major', 'Majeure'), ('minor', 'Mineure'), ('trivial', 'Triviale')], default='major', max_length=10)),
                ('priority', models.CharField(choices=[('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé'), ('reopened', 'Réouvert')], default='open', max_length=12)),
                ('steps_to_reproduce', models.TextField(blank=True)),
                ('expected_behavior', models.TextField(blank=True)),
                ('actual_behavior', models.TextField(blank=True)),
                ('environment', models.CharField(blank=True, help_text='Navigateur, OS, version…', max_length=200)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='defects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='teams.project')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='core.extractedusecase')),
            ],
            options={
                'verbose_name': 'Anomalie',
                'verbose_name_plural': 'Anomalies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('goal', models.TextField(blank=True, help_text='Objectif du sprint')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('active', 'En cours'), ('completed', 'Terminé'), ('closed', 'Clôturé')], default='planned', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sprints', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='teams.project')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UseCaseComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_comments', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.extractedusecase')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UseCaseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='À tester', max_length=20)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_assignments', to='teams.projectmember')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='qamanagement.sprint')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.extractedusecase')),
            ],
            options={
                'verbose_name': 'Affectation de cas',
                'verbose_name_plural': 'Affectations de cas',
                'ordering': ['assigned_at'],
                'unique_together': {('use_case', 'assigned_to')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField(help_text='Lundi de la semaine')),
                ('week_end', models.DateField(help_text='Dimanche de la semaine')),
                ('accomplishments', models.TextField(blank=True, help_text='Ce qui a été accompli cette semaine')),
                ('blockers', models.TextField(blank=True, help_text='Problèmes rencontrés / blocages')),
                ('next_week_plans', models.TextField(blank=True, help_text='Prévisions pour la semaine prochaine')),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis')], default='draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport hebdomadaire',
                'verbose_name_plural': 'Rapports hebdomadaires',
                'ordering': ['-week_start'],
                'unique_together': {('user', 'team', 'week_start')},
            },
        ),
    ]
