# Generated by Django 5.0.6 on 2026-05-19 11:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('DONE', 'Terminé'), ('ERROR', 'Erreur')], default='PENDING', max_length=20)),
                ('source_filename', models.CharField(max_length=255)),
                ('word_file', models.FileField(upload_to='uploads/word/')),
                ('excel_template', models.FileField(blank=True, null=True, upload_to='uploads/templates/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('use_cases_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tâche de conversion',
                'verbose_name_plural': 'Tâches de conversion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedUseCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('use_case_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preconditions', models.TextField(blank=True)),
                ('steps', models.TextField(blank=True)),
                ('expected_results', models.TextField(blank=True)),
                ('observed_results', models.TextField(blank=True)),
                ('is_automated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('À tester', 'À tester'), ('En cours', 'En cours'), ('Passé', 'Passé'), ('Échoué', 'Échoué'), ('Bloqué', 'Bloqué')], default='À tester', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='core.conversionjob')),
            ],
            options={
                'verbose_name': 'Use Case extrait',
                'verbose_name_plural': 'Use Cases extraits',
                'ordering': ['order'],
            },
        ),
    ]
