# Generated by Django 6.0.5 on 2026-05-25 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_header'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_jobs', to='teams.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par'),
        ),
    ]
