# Generated by Django 5.1.15 on 2026-06-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_use_case_id_to_use_case_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedusecase',
            name='use_case_text',
            field=models.TextField(blank=True),
        ),
    ]
