# Generated by Django 5.2.17 on 2026-09-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_extractedusecase_use_case_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedusecase',
            name='jira_ticket',
            field=models.CharField(blank=True, default='', help_text='Numéro du ticket Jira lié à ce cas de test (ex : QA-123)', max_length=100, verbose_name='Ticket Jira'),
        ),
    ]
